In [1]:
import numpy as np
import pandas as pd

In [2]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10, 3)

In [5]:
zeros_array = np.zeros(10)
print(constant_array)

[3 3 3 3 3 3 3 3 3 3]


In [6]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)
print(array_from_list)
print(my_list)

[2 3 4]
[2, 3, 4]


In [7]:
linspace_array = np.linspace(0, 1, 9)
print(linspace_array)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [8]:
zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2), 3)

In [11]:
print(constant_matrix)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [27]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[1:, 0]  # Gets the first column

print(arr)
#print(first_row)
#print(first_col)
print(arr[:1,1])

[[2 3 4]
 [4 5 6]]
[3]


In [22]:
np.random.seed(3)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1

print(random_array)


[[0.5507979  0.70814782]
 [0.29090474 0.51082761]
 [0.89294695 0.89629309]
 [0.12558531 0.20724288]
 [0.0514672  0.44080984]]


In [30]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=10, size=(5, 2))

In [31]:
print(normal_distribution)
print('/n')
print(random_integers)

[[-0.53463016 -1.32688896]
 [ 0.66805241  0.28587781]
 [-0.37067527  1.05045112]
 [ 0.2613125  -0.69459727]
 [-2.02469194  0.84595316]]
/n
[[1 5]
 [5 7]
 [4 3]
 [0 0]
 [0 0]]


In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv', encoding='utf=8')

In [8]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [9]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [23]:
dell = df[df['Brand'] == 'Dell']

In [27]:
dell['Final Price'].max()

3936.0

In [29]:
df['Screen'].median()

15.6

In [30]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [31]:
df['Screen'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2160 entries, 0 to 2159
Series name: Screen
Non-Null Count  Dtype  
--------------  -----  
2156 non-null   float64
dtypes: float64(1)
memory usage: 17.0 KB


In [34]:
df['Screen'].fillna(df['Screen'].mode()).info()

<class 'pandas.core.series.Series'>
RangeIndex: 2160 entries, 0 to 2159
Series name: Screen
Non-Null Count  Dtype  
--------------  -----  
2156 non-null   float64
dtypes: float64(1)
memory usage: 17.0 KB


In [35]:
df['Screen'].median()

15.6

In [39]:
Innjoo 

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [41]:
Innjoo.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [48]:
Innjoo[['RAM','Storage','Screen']].head()

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1